import Head from 'next/head'
import { Inter } from 'next/font/google'
import { MenuItem } from '@/components/MenuItem'
import { InfoPanel } from '@/components/InfoPanel'
import AmplifyAuthenticator from '@/components/AmplifyAuthenticator'






const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>


      {/* <MenuItem itemText='Monthly Gifts' buttonText='View and Manage'/>
      <InfoPanel/> */}
      <AmplifyAuthenticator/>

      </main>
    </>
  )
}
